version: '3.7'

services:
  db:
    image: mysql:5.7
    #restart: always
    container_name: nfest-5.6-db
    command: mysqld --sql_mode=""
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: nfest
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql

  app:
    build:
      context: .docker
    container_name: nfest-5.6
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    links:
      - db
    
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    #restart: always
    container_name: nfest-5.6-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 10000M

networks:
  default:
    external:
      name: external-network

# docker-compose up -d
# docker-compose up -d --build
# docker exec -it e07e248f2817 bash
# docker-compose build --no-cache --force-rm nombredelservicio(db,app,phpmyadmin)
# docker stop $(docker ps -a -q)
# docker inspect 2473635319d0 | grep IPAddress
# docker network create <network name>